### PR TITLE
Code style review for pots branch

### PR DESCRIPTION
**Pull request by fenhl**
Includes a bunch of small changes, none of which should change the behavior of any code.

I also removed the readme and version changes. This branch is in the awkward position of being both a PR branch and a personal branch, but the PR should be getting merged soon and I don't want any confusion from these changes accidentally being merged.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Man I tried so hard to find all those extra spaces at the ends of lines...

**Comment by fenhl** [comment]
If you're using VS Code, I recommend the [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) extension. Makes them really obvious.

**Comment by r0bd0g** [comment]
I'm using notepad :p

**Comment by fenhl** [comment]
In that case, I highly recommend VS Code. Makes working on a codebase a lot nicer.

**Pull request merged**
