### PR TITLE
Move new item IDs to 0x0200

### PR DESCRIPTION
**Pull request by fenhl**
This reverts the IDs of items exclusive to this fork to what they were before the 8.2.x merge, fixing auto-trackers and the send-all feature in [Mido's House Multiworld](https://github.com/midoshouse/ootr-multiworld).

### CODE REVIEW

**Comment by rrealmuto** [comment]
So while I was updating my branch with the new item_table format I realized how RAM/ROM wasteful it was to move those items up into the 0x2000 range. it's like 220KB

Sizes of item_table:
With the items in the 0x2000 range
```
0x39CE0
```

Without the items in the 0x2000 range
```
0x29AC
```

So I ended up moving them back down into the normal range. Perhaps I can add a small buffer (like 20 or so) to give room for upstream to expand before I have to go and update IDs again, but I don't want to move it back to the 0x2000 range. Sorry if that breaks autotrackers/MH

**Comment by fenhl** [comment]
Maybe something like `0x0200` would work? The important part is that the IDs don't change frequently, as each change means a manual update which also breaks compatibility with older versions of your branch.

**Comment by rrealmuto** [comment]
0x0200 is definitely more reasonable. I don't see people coming up with another ~200 items in the near future lol

**Comment by fenhl** [comment]
Done, sorry about the delay.

**Pull request merged**
